### ISSUE TITLE
Output suggest writes that are not actually required nor performed

### ISSUE THREAD

**Issue by jakob-keller** [lorenzwalthert/gitignore-tidy#3]
Hoi Lorenz!

The following output was generated when executing `pre-commit run --all-files` on a repo with three .gitignore files:

> Sort entries in gitignore................................................Failed
> - hook id: tidy-gitignore
> - files were modified by this hook
> 
> Successfully written .gitignore.
> .idea/.gitignore already tidy.
> Successfully written .idea/.gitignore.
> x-y-z.abc/.gitignore already tidy.
> Successfully written x-y-z.abc/.gitignore.

The behaviour makes perfect sense, one out of three files were successfully fixed. However, for all three files the output reads `Successfully written`, which appears misleading. Is this intended behaviour?

By the way, after the initial run, the pre-commit hook succeeds and no such lines are printed, which is what I'd expect.

Great project, keep it up!

**Comment by lorenzwalthert** [comment]
Thanks @jakob-keller, you are right. I forgot that you need [`raise` in front of `typer.exit()`](https://github.com/lorenzwalthert/gitignore-tidy/pull/4/commits/6d40a6f472633b91d58ee2da406d21d755060d76#diff-574b497d1fcf564599f30bb4556a9f35747b7da1aa92c0dc549b0ad5ac6f315eL112). Fixed with #4 with tighter unit test.

**Comment by lorenzwalthert** [comment]
With another round of `pre-commit autoupdate`, the problem should be solved. Also, note that by default, pre-commit prints any output only if a hook fails (which is the case if the hook script exits with non-zero or a file is modified).

**Comment by jakob-keller** [comment]
Great, fantastic reaction time, despite holiday season ;-)

Short follow-up: With c173e0fe7aee19caff23c96478564465605b1905, the output now looks like this:

> Sort entries in gitignore................................................Failed
> - hook id: tidy-gitignore
> - files were modified by this hook
> 
> Successfully written .gitignore.
> .idea/.gitignore already tidy.

This suggests to me that x-y-z.abc/.gitignore is no longer picked up, which is probably untrue. Is the previous line `x-y-z.abc/.gitignore already tidy.` missing?

**Comment by lorenzwalthert** [comment]
In fact no, I made it worse 😢. `raise typer.Exit()` quit the whole program when looping through all files. What's needed with the latest refactoring is a simple `return` (48c410f2549bfea6d4cb3a712df73017dd540904). Does it work after another `pre-commit autoupdate`?

**Comment by lorenzwalthert** [comment]
All these bugs I produced today... Quite unbelievable. All with 100% test coverage -.-

**Comment by jakob-keller** [comment]
> In fact no, I made it worse 😢. `raise typer.Exit()` quit the whole program when looping through all files. What's needed with the latest refactoring is a simple `return` ([48c410f](https://github.com/lorenzwalthert/gitignore-tidy/commit/48c410f2549bfea6d4cb3a712df73017dd540904)). Does it work after another `pre-commit autoupdate`?

Indeed, works like a charm now:

> Sort entries in gitignore................................................Failed
> - hook id: tidy-gitignore
> - files were modified by this hook
> 
> Successfully written .gitignore.
> .idea/.gitignore already tidy.
> x-y-z.abc/.gitignore already tidy.

**Comment by lorenzwalthert** [comment]
Note that I can't (yet) guarantee that every case is handled correctly, i.e. that wild cards in conjunction with `!` are correctly treated. All it currently does is what's stated in the readme.
